version: "3.9"

services:
  directiva-handler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: directiva-handler
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - cooperativa-net

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - cooperativa-net

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - cooperativa-net

volumes:
  postgres-data:
  redis-data:

networks:
  cooperativa-net:
    driver: bridge
